### PR TITLE
Fix compilation errors in ubuntu 20.04 fresh image

### PR DESCRIPTION
**Pull request by not-in-stock**
This set of changes fixes compilation errors on Ubuntu 20.04.
It also works on Ubuntu 18.04.

### CODE REVIEW

**Comment by Guite** [comment]
Works fine :+1:

**Comment by mareksuscak** [comment]
Also FYI @not-in-stock - added you to our [hall of fame](https://github.com/mareksuscak/asus-pce-n53-linux/blob/master/README.md#contributors). Hope you don't mind it.

**Comment by mareksuscak** [comment]
FYI no. 2 @Guite since you're a pretty active member here. I've just invited you to become a collaborator.

**Comment by Guite** [comment]
> I've just invited you to become a collaborator.

Thanks.

**Comment by not-in-stock** [comment]
> Also FYI @not-in-stock - added you to our [hall of fame](https://github.com/mareksuscak/asus-pce-n53-linux/blob/master/README.md#contributors). Hope you don't mind it.

Thanks a lot for the mention!
P.S. it looks like that profile link is accidentally duplicated :)

**Comment by mareksuscak** [comment]
Apologies, fixed.
